### ISSUE TITLE
Custom font only loads when you use the navbar

### ISSUE THREAD

**Issue by HearToWear** [HearToWear/BlackCon#4]
Anyone having the problem where the custom font only loads when you hover over the navbar? Or is that just me?

**Comment by TheArchiteck** [comment]
I think it may just be you. I switched to NaxaneTheme to see, and I've found no difference in fonts between before and after swiping over the navbar.

Either that, or I'm not even seeing a custom font at all. But the font family on my browser console does say "Lato", so I assume that's not the case.

**Comment by TheArchiteck** [comment]
Yep, I have confirmation that the custom font is staying loaded even without hovering over the navbar. It's probably just Wikidot being a jerk chicken, which means it will likely pass.

I'll just be closing this, I guess.
